eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      uri:  mongodb://localhost:27018/orderdb
      host: localhost
      port: 27018
      database: orderdb
      repositories:
        enabled: true